DROP TABLE IF EXISTS EST_PCT;
DROP TABLE IF EXISTS PCT_AVLC;
DROP TABLE IF EXISTS EST_AVLC_QSTN;
DROP TABLE IF EXISTS AVLC_QSTN;
DROP TABLE IF EXISTS SITM_QSTN;
DROP TABLE IF EXISTS GR_SITM_QSTN;
DROP TABLE IF EXISTS ITEM_QSTN;
DROP TABLE IF EXISTS GR_ITEM_QSTN;
DROP TABLE IF EXISTS EST_QSTN;
DROP TABLE IF EXISTS QSTN;



-- questionario
CREATE TABLE QSTN (
		  CD_QSTN INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, 
		  NM_QSTN CHAR(254 OCTETS) , 
		  CD_TIP_QSTN SMALLINT NOT NULL , 
		  CD_TIP_EST_QSTN SMALLINT NOT NULL,
		  TS_INC_VLDD_QSTN TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		  TS_FIM_VLDD_QSTN TIMESTAMP,
		  TX_OBJT_QSTN VARCHAR(1200 OCTETS) , 
		  TX_AJD_QSTN VARCHAR(1200 OCTETS) , 
		  DT_REG_QSTN DATE
 ) ;

CREATE TABLE EST_QSTN (
	CD_QSTN INTEGER NOT NULL,
	CD_EST_QSTN SMALLINT NOT NULL,
	TS_INC_EST TIMESTAMP NOT NULL,
	TS_FIM_EST TIMESTAMP NOT NULL,
	CD_USU_RSP_ATL INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY (CD_QSTN, CD_EST_QSTN, TS_INC_EST),
	FOREIGN KEY (CD_QSTN) REFERENCES QSTN (CD_QSTN)
);

-- grupo item

CREATE TABLE GR_ITEM_QSTN (
	  CD_GR_ITEM INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT , 
	  CD_QSTN INTEGER NOT NULL , 
	  NR_ORD_GR_ITEM SMALLINT NOT NULL DEFAULT 0, 
	  NM_GR_ITEM CHAR(254 OCTETS) , 
	  TX_AJD_GR_ITEM VARCHAR(1200 OCTETS) , 
	  IN_UTZO_GR_ITEM CHAR(1 OCTETS),
	 FOREIGN KEY (CD_QSTN) REFERENCES QSTN (CD_QSTN));

	
-- item
CREATE TABLE ITEM_QSTN  (
		  CD_ITEM INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, 
		  CD_GR_ITEM INTEGER NOT NULL, 
		  NR_ORD_ITEM SMALLINT NOT NULL DEFAULT 0, 
		  IN_UTZO_ITEM CHAR(1 OCTETS) NOT NULL DEFAULT 'S',
  		  TX_ITEM VARCHAR(1200 OCTETS),
		  TX_AJD_ITEM VARCHAR(1200 OCTETS),
		  FOREIGN KEY (CD_GR_ITEM) REFERENCES GR_ITEM_QSTN (CD_GR_ITEM)
 );

-- grupo subitem
CREATE TABLE GR_SITM_QSTN  (
		  CD_GR_SITM INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT , 
		  CD_ITEM INTEGER NOT NULL , 
		  NR_ORD_GR_SITM SMALLINT NOT NULL DEFAULT 0, 
		  TX_GR_SITM CHAR(254 OCTETS) , 
		  CD_TIP_GR_SITM SMALLINT NOT NULL , 
		  IN_UTZO_GR_SITM CHAR(1 OCTETS),
		  FOREIGN KEY (CD_ITEM) REFERENCES ITEM_QSTN (CD_ITEM)
		 ) ;
		 

-- subitem
CREATE TABLE SITM_QSTN  (
		  CD_SITM INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, 
		  CD_GR_SITM INTEGER NOT NULL , 
		  NR_ORD_SITM SMALLINT NOT NULL DEFAULT 0,
		  TX_SITM CHAR(254 OCTETS) ,
		  VL_INC_ITVL_SITM DECIMAL(17,2),
		  VL_FIM_ITVL_SITM DECIMAL(17,2),
		  QT_PTO_SITM SMALLINT,
		  FOREIGN KEY (CD_GR_SITM) REFERENCES GR_SITM_QSTN (CD_GR_SITM)
		  );   
		 
-- avaliacao do questionario
CREATE TABLE AVLC_QSTN (
	CD_AVLC INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	CD_QSTN INTEGER NOT NULL,
	CD_TIP_EST SMALLINT NOT NULL,
	CD_TIP_AVLC SMALLINT NOT NULL,
	TS_INC_AVLC TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	TS_FIM_AVLC TIMESTAMP,
	TX_DCR_AVLC_QSTN VARCHAR(2000 OCTETS) NOT NULL DEFAULT '',
	FOREIGN KEY (CD_QSTN) REFERENCES QSTN (CD_QSTN)
);	

-- ESTASO AVLC
CREATE TABLE EST_AVLC_QSTN (
	CD_AVLC INTEGER NOT NULL,
	CD_TIP_EST SMALLINT NOT NULL,
	TS_INC_EST TIMESTAMP NOT NULL,
	TS_FIM_EST TIMESTAMP,
	CD_USU_RSP_ATL INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY (CD_AVLC, CD_TIP_EST, TS_INC_EST),
	FOREIGN KEY (CD_AVLC) REFERENCES AVLC_QSTN (CD_AVLC)
);


-- participante da avaliacao
CREATE TABLE PCT_AVLC (
	CD_PCT INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	CD_AVLC INTEGER NOT NULL,
	CD_TIP_PCT SMALLINT NOT NULL,
	CD_TIP_EST_PCT SMALLINT NOT NULL,
	CD_USU INTEGER NOT NULL DEFAULT 0,
	TS_INC_PCT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	TS_FIM_PCT TIMESTAMP,
	FOREIGN KEY (CD_AVLC) REFERENCES AVLC_QSTN (CD_AVLC)
);

-- estado pct

CREATE TABLE EST_PCT (
	CD_PCT INTEGER NOT NULL,
	CD_TIP_EST SMALLINT NOT NULL,
	TS_INC_EST TIMESTAMP NOT NULL,
	TS_FIM_EST TIMESTAMP,
	CD_USU_RSP_ATL INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY (CD_PCT, CD_TIP_EST, TS_INC_EST),
	FOREIGN KEY (CD_PCT) REFERENCES PCT_AVLC (CD_PCT) 
);
