DROP TABLE IF EXISTS PCT_AVLC;
DROP TABLE IF EXISTS AVLC_QSTN;
DROP TABLE IF EXISTS SITM_QSTN;
DROP TABLE IF EXISTS GR_SITM_QSTN;
DROP TABLE IF EXISTS ITEM_QSTN;
DROP TABLE IF EXISTS GR_ITEM_QSTN;
DROP TABLE IF EXISTS QSTN;
DROP TABLE IF EXISTS TIP_QSTN;
DROP TABLE IF EXISTS TIP_GR_SITM;
DROP TABLE IF EXISTS TIP_EST_QSTN;
DROP TABLE IF EXISTS TIP_EST_AVLC;
DROP TABLE IF EXISTS TIP_AVLC;
DROP TABLE IF EXISTS TIP_EST_PCT;
DROP TABLE IF EXISTS TIP_PCT;


-- tipos
CREATE TABLE TIP_QSTN (
		  CD_TIP_QSTN INTEGER NOT NULL PRIMARY KEY, 
		  NM_TIP_QSTN CHAR(100 OCTETS) NOT NULL , 
		  TX_DCR_TIP_QSTN CHAR(254 OCTETS) , 
		  IN_UTZO_TIP CHAR(1 OCTETS) );
		 
CREATE TABLE TIP_GR_SITM  (
		  CD_TIP_GR_SITM INTEGER NOT NULL , 
		  NM_TIP_GR_SITM CHAR(100 OCTETS) , 
		  TX_DCR_TIP_GR_SITM CHAR(254 OCTETS) , 
		  IN_UTZO_TIP_GR CHAR(1 OCTETS) );
		 
CREATE TABLE TIP_EST_QSTN (
	CD_TIP_EST_QSTN INTEGER NOT NULL PRIMARY KEY,
	NM_TIP_EST_QSTN CHAR(20) NOT NULL
);
		 
CREATE TABLE TIP_EST_AVLC (
	CD_TIP_EST_AVLC INTEGER NOT NULL PRIMARY KEY,
	NM_TIP_EST_AVLC CHAR(20) NOT NULL
);

CREATE TABLE TIP_AVLC (
	CD_TIP_AVLC INTEGER NOT NULL PRIMARY KEY,
	NM_TIP_AVLC CHAR(20) NOT NULL
);

CREATE TABLE TIP_EST_PCT (
	CD_TIP_EST_PCT INTEGER NOT NULL PRIMARY KEY,
	NM_TIP_EST_PCT CHAR(20) NOT NULL DEFAULT ''
);

CREATE TABLE TIP_PCT (
	CD_TIP_PCT INTEGER NOT NULL PRIMARY KEY,
	NM_TIP_PCT CHAR(20) NOT NULL DEFAULT ''
);

-- questionario
CREATE TABLE QSTN (
		  CD_QSTN INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, 
		  NM_QSTN CHAR(254 OCTETS) , 
		  CD_TIP_QSTN INTEGER NOT NULL , 
		  CD_TIP_EST_QSTN INTEGER NOT NULL, 
		  TX_OBJT_QSTN VARCHAR(1200 OCTETS) , 
		  TX_AJD_QSTN VARCHAR(1200 OCTETS) , 
		  DT_REG_QSTN DATE,
		  FOREIGN KEY (CD_TIP_QSTN) REFERENCES TIP_QSTN (CD_TIP_QSTN),
		  FOREIGN KEY (CD_TIP_EST_QSTN) REFERENCES TIP_EST_QSTN (CD_TIP_EST_QSTN)
 ) ;

-- grupo item

CREATE TABLE GR_ITEM_QSTN (
	  CD_GR_ITEM INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT , 
	  CD_QSTN INTEGER NOT NULL , 
	  NR_ORD_GR_ITEM INTEGER NOT NULL DEFAULT 0, 
	  NM_GR_ITEM CHAR(254 OCTETS) , 
	  TX_AJD_GR_ITEM VARCHAR(1200 OCTETS) , 
	  IN_UTZO_GR_ITEM CHAR(1 OCTETS),
	 FOREIGN KEY (CD_QSTN) REFERENCES QSTN (CD_QSTN));

	
-- item
CREATE TABLE ITEM_QSTN  (
		  CD_ITEM INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, 
		  CD_GR_ITEM INTEGER NOT NULL, 
		  NR_ORD_ITEM INTEGER NOT NULL DEFAULT 0, 
		  IN_UTZO_VCL CHAR(1 OCTETS) NOT NULL DEFAULT 'S', 
		  TX_AJD_ITEM VARCHAR(1200 OCTETS),
		  FOREIGN KEY (CD_GR_ITEM) REFERENCES GR_ITEM_QSTN (CD_GR_ITEM)
 );

-- grupo subitem
CREATE TABLE GR_SITM_QSTN  (
		  CD_GR_SITM INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT , 
		  CD_ITEM INTEGER NOT NULL , 
		  NR_ORD_GR_SITM INTEGER , 
		  TX_GR_SITM CHAR(254 OCTETS) , 
		  CD_TIP_GR_SITM INTEGER NOT NULL , 
		  IN_UTZO_GR_SITM CHAR(1 OCTETS),
		  FOREIGN KEY (CD_ITEM) REFERENCES ITEM_QSTN (CD_ITEM)
		 ) ;
		 

-- subitem
CREATE TABLE SITM_QSTN  (
		  CD_SITM INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, 
		  CD_GR_SITM INTEGER NOT NULL , 
		  NR_ORD_SITM INTEGER NOT NULL DEFAULT 0,
		  TX_SITM CHAR(254 OCTETS) ,
		  VL_INC_ITVL_SITM DECIMAL(17,2),
		  VL_FIM_ITVL_SITM DECIMAL(17,2),
		  QT_PTO_SITM SMALLINT,
		  FOREIGN KEY (CD_GR_SITM) REFERENCES GR_SITM_QSTN (CD_GR_SITM)
		  );   
		 
-- avaliacao do questionario
CREATE TABLE AVLC_QSTN (
	CD_AVLC INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	CD_QSTN INTEGER NOT NULL,
	CD_TIP_EST_AVLC INTEGER NOT NULL,
	CD_TIP_AVLC INTEGER NOT NULL,
	TX_DCR_AVLC_QSTN VARCHAR(2000 OCTETS) NOT NULL DEFAULT '',
	FOREIGN KEY (CD_QSTN) REFERENCES QSTN (CD_QSTN),
	FOREIGN KEY (CD_TIP_EST_AVLC) REFERENCES TIP_EST_AVLC (CD_TIP_EST_AVLC),
	FOREIGN KEY (CD_TIP_AVLC) REFERENCES TIP_AVLC (CD_TIP_AVLC)
);	


-- participante da avaliacao
CREATE TABLE PCT_AVLC (
	CD_PCT INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	CD_AVLC INTEGER NOT NULL,
	CD_TIP_PCT INTEGER NOT NULL,
	CD_TIP_EST_PCT INTEGER NOT NULL,
	FOREIGN KEY (CD_AVLC) REFERENCES AVLC_QSTN (CD_AVLC),
	FOREIGN KEY (CD_TIP_PCT) REFERENCES TIP_PCT (CD_TIP_PCT),
	FOREIGN KEY (CD_TIP_EST_PCT) REFERENCES TIP_EST_PCT (CD_TIP_EST_PCT)
);